# Workflow name
name: hello

# Runs on a trigger
on:
  push:
    branches:
      - main
    paths: 
      -'**.html'

# Jobs inside the workflow
jobs:
  # Job name
  greet:
    # GitHub runner
    runs-on: ubuntu-latest

    steps:
      - name: Say hello to user
        run: echo "hello dosto"

      - name: Say hello to username
        run: echo "hi $USER"

  details:
    runs-on: ubuntu-latest

    steps:
      - name: Show Docker and Python versions
        run: docker --version && python --version
